# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Amine Sahibi
tagline:          'Bang'
description:      'Software engineer, waterman, avid reader and aspiring minimalist'
url:              https://amines.github.io
baseurl:          /

author:
  name:           'Amine Sahibi'
  url:            https://amines.github.io

# Gems
gems: [jekyll-paginate]

# Paginate
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://amines.github.io/
